Fix build with DEBUG defined
Move up the struct declaration so we can use it
in the DEBUG block.

fribidi-bidi.c:264:33: error: unknown type name ‘FriBidiPairingNode’; did you mean ‘FriBidiParType’?
static void print_pairing_nodes(FriBidiPairingNode *nodes)